apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bikeflow
resources:
  - namespace.yaml
  - configmap.yaml
  - mongo-service.yaml
  - mongo-statefulset.yaml
  - mongo-init-job.yaml
  - backend-deployment.yaml
  - backend-service.yaml

