apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: bikeflow
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: bikeflow
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb

